### ISSUE TITLE
Add basic meta data to site pages for SEO purposes

### ISSUE THREAD

**Issue by ldhandley** [srfoster/codespells.org#2]

**Comment by jesscxc** [comment]
eg `<title>`

How hard is this to do with the framework?

Does codespells.org use a custom framework or?

**Comment by ldhandley** [comment]
Theoretically it isn't hard. We've definitely done it for other websites that use this framework! I'm in the middle of working on it now. Having to do a little re-architecting, but I think I'm getting close!

**Comment by ldhandley** [comment]
See 5baec980d36ef1716924fefd5f465f1c5808811a
